![alt text](<../images/just enough.png>)
# Just Enough Python for AI/Data Science
## Module 3: Numpy- Your First Data Science Power Tool
>This module will ensure you can wrangle numerical data efficiently before tackling larger datasets with pandas. It’s just enough to prep you for serious data crunching.
### Day 7 - Meet Numpy: The Swiss Army Knife of Arrays
----

##### Overview:

Numpy is one of the most popular libraries in Data Science. If Python is your toolbox, think of Numpy as your Swiss Army Knife—it helps you handle data more efficiently and lays the foundation for working with more complex data tools like Pandas and Scikit-Learn.

Today we will understand:

- Why Numpy is critical for data science.
- How to create and manipulate **Numpy arrays**.
- The basics of **array operations, indexing, reshaping, and slicing**.

#### 1. What Is Numpy and Why Do We Need It?
**Why Not Just Use Python Lists?**
Python lists are versatile, but they have limitations:

- 1. **Inefficient Memory Use:** Lists store references to objects, wasting memory.
- 2. **Slow for Numerical Operations:** Lists require looping through elements, while Numpy operates on vectors for faster computations.
- 3. **No Advanced Mathematical Operations:** To perform calculations like matrix operations, you need additional code or libraries.

**Numpy to the Rescue**
Numpy (**Numerical Python**) is designed for **efficient numerical computing**. It brings:

- 1. **Fast Operations:** Written in C, Numpy is much faster than lists for numerical operations.
- 2. **Compact Storage:** Arrays are stored in fixed-size memory blocks, saving space.
- 3. **Advanced Capabilities:** Built-in functions handle linear algebra, statistics, and data wrangling with ease.
- 4. **Array Broadcasting:** Perform operations on entire arrays without writing loops.

**Install Numpy**

Before we begin, make sure Numpy is installed:

In [1]:
# !pip3 install numpy


#### 2. Making Your First Numpy Array
A Numpy array is like a list, but faster, more compact, and designed explicitly for mathematical calculations.

**Basic Array Creation**
Import Numpy and create simple arrays.

In [1]:
import numpy as np

In [2]:
# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D array:", array_1d)

# Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", array_2d)


1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]


**Differences from Python Lists**

In [3]:
# Python list vs Numpy array
python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])

# Example: Add 2 to each element
# print("Numpy array + 2:", python_list + 2)
print("Python list + 2 (Error!):", [x + 2 for x in python_list])
print("Numpy array + 2:", numpy_array + 2)


Python list + 2 (Error!): [3, 4, 5]
Numpy array + 2: [3 4 5]


#### 3. Numpy Advantages: Array Operations
**Arithmetic Operations**
- Perform operations on entire arrays at once (element-wise operations).

In [4]:
array = np.array([1, 2, 3, 4, 5])

# Element-wise operations
print("Add 2:", array + 2)
print("Multiply by 3:", array * 3)
print("Square each element:", array ** 2)


Add 2: [3 4 5 6 7]
Multiply by 3: [ 3  6  9 12 15]
Square each element: [ 1  4  9 16 25]


**Array Comparisons**

- Compare and filter elements easily.

In [5]:
print("Array > 3:", array > 3)
print("Array == 3:", array == 3)


Array > 3: [False False False  True  True]
Array == 3: [False False  True False False]


#### 4. Array Dimensions and Shapes
- Understanding the shape of an array is critical when working with multi-dimensional data.
- **Check Array Dimensions**

In [6]:
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

print("1D array shape:", array_1d.shape)
print("2D array shape:", array_2d.shape)
print("Number of dimensions (ndim):", array_2d.ndim)
print("Number of elements (size):", array_2d.size)

1D array shape: (5,)
2D array shape: (2, 3)
Number of dimensions (ndim): 2
Number of elements (size): 6


**Reshaping Arrays**
- Reshape arrays to different dimensions using `.reshape()`.

In [7]:
array = np.array([1, 2, 3, 4, 5, 6])

# Reshape to 2x3
reshaped = array.reshape(2, 3)
print("Reshaped to 2x3:\n", reshaped)

# Reshape back to 1D
flattened = reshaped.ravel()
print("Flattened to 1D:", flattened)


Reshaped to 2x3:
 [[1 2 3]
 [4 5 6]]
Flattened to 1D: [1 2 3 4 5 6]


In [8]:
array_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    
    [[7, 8, 9], [10, 11, 12]]
])
print("3D array shape:", array_3d.shape)
print("Number of dimensions:", array_3d.ndim)
print(array_3d)

3D array shape: (2, 2, 3)
Number of dimensions: 3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


#### 5. Indexing and Slicing

**Indexing**
- Access elements using indices, similar to lists.

In [9]:
array = np.array([10, 20, 30, 40, 50])

# Access specific elements
print("First element:", array[0])
print("Last element:", array[-1])

# Access elements in a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Element at [1, 2]:", array_2d[1, 2])  # Row 1, Column 2
print("Row 1:", array_2d[1])  # Row 1

First element: 10
Last element: 50
Element at [1, 2]: 6
Row 1: [4 5 6]


**Slicing**
- Retrieve subsets of an array efficiently.



In [10]:
# Slicing in 1D array
array = np.array([10, 20, 30, 40, 50])
print("Elements 1st to 3rd:", array[0:3])

# Slicing in 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("First row:", array_2d[0, :])  # All columns of the first row
print("First column:", array_2d[:, 0])  # All rows of the first column


Elements 1st to 3rd: [10 20 30]
First row: [1 2 3]
First column: [1 4]


**Fancy Indexing and Boolean Masks**

In [11]:
array = np.array([10, 20, 30, 40, 50])

# Fancy indexing (using a list of indices)
print("Select indices 1, 3, and 4:", array[[1, 3, 4]])

# Boolean mask
print("Elements > 30:", array[array > 30])  # Select elements greater than 30


Select indices 1, 3, and 4: [20 40 50]
Elements > 30: [40 50]


#### 6. Creating Arrays: Useful Numpy Functions
- Numpy provides several methods to generate arrays with specific patterns or values.

**Arrays of Zeros and Ones**
- Used for initializing arrays.

In [12]:

# Array of zeros
zeros = np.zeros((2, 3))
print("Zeros:\n", zeros)

# Array of ones
ones = np.ones((3, 2))
print("Ones:\n", ones)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


**Arrays with a Range of Numbers**
- Generate a sequence of values.

In [13]:
# Similar to Python's range()
range_array = np.arange(0, 10, 2)
print("Range array:", range_array)

# Linearly spaced array
linspace_array = np.linspace(0, 1, 5)  # 5 values between 0 and 1
print("Linspace array:", linspace_array)


Range array: [0 2 4 6 8]
Linspace array: [0.   0.25 0.5  0.75 1.  ]


**Random Arrays**
- Useful for simulations or initializing weights in deep learning.

In [14]:
# Random values between 0 and 1
random_array = np.random.rand(3, 2)
print("Random array:\n", random_array)

# Random integers
random_integers = np.random.randint(0, 10, (2, 2))  # Integers between 0 and 10
print("Random integers:\n", random_integers)


Random array:
 [[0.38007538 0.3326601 ]
 [0.4502289  0.3804497 ]
 [0.63897426 0.1518766 ]]
Random integers:
 [[0 8]
 [1 2]]


#### 7. Copying vs Viewing Arrays
- Be careful when copying or slicing arrays. Numpy distinguishes between views (linked to the original data) and copies (independent).

In [15]:
array = np.array([1, 2, 3, 4, 5])

# View (changes affect the original array)
view = array[1:3]
print("view", view)
view[0] = 99
print("Original array after view change:", array)

# Copy (changes do NOT affect the original array)
copy = array[1:3].copy()
print("copy", copy)
copy[0] = 88
print("Original array after copy change:", array)
print("Copy after change:", copy)



view [2 3]
Original array after view change: [ 1 99  3  4  5]
copy [99  3]
Original array after copy change: [ 1 99  3  4  5]
Copy after change: [88  3]


----
#### Quick Exercises
1. Create the following arrays using Numpy:

    - A 1D array with values from 10 to 50.
    - A 2D array of zeros with shape (4, 3).
    - A random 2x2 matrix.

2. Perform the following operations:

    - Add 5 to every element of an array.
    - Select all elements greater than 25 in an array.


3. Reshape a 1D array of size 12 into a 3x4 matrix.

4. Slice a 2D array to extract:

    - The first row.
    - All rows, but only the second column.


**Please Note:** The solutions to above questions will be present at the end of next session's (Day 8- Basic Data Math with Numpy) Notebook.


---- 


### Day 6 Exercise Solution

1. Create a greeting function that takes a name and age and says:

    - `"Hello, [name]! You are [age] years old."`

In [16]:
def greet(name, age):
    return f"Hello, {name}! You are {age} years old."

# Example usage
print(greet("Babu Rao", 48))


Hello, Babu Rao! You are 48 years old.


2. Write a function to calculate the area of a rectangle with default parameters length=10 and width=5.

In [17]:
def rectangle_area(length=10, width=5):
    return length * width

# Example usage
print(rectangle_area())        # Uses default values: 10 * 5 = 50
print(rectangle_area(7, 3))    # Custom values: 7 * 3 = 21


50
21


3. Create a function is_even() that takes a number and returns True if it’s even, and False otherwise.

In [18]:
def is_even(number):
    return number % 2 == 0

# Example usage
print(is_even(10))  # True
print(is_even(7))   # False


True
False


4. Write a function process_list() that takes a list of numbers and:
    - Removes duplicates,
    - Sorts the list in ascending order, and
    - Returns the cleaned list.
    - Use a lambda function inside Python’s filter() to extract all even numbers from the list:
        - `numbers = [3, 6, 8, 7, 5, 9, 2]`

In [22]:
def process_list(numbers):
    # Remove duplicates and sort
    cleaned_list = sorted(set(numbers))

    # Extract even numbers using filter + lambda
    even_numbers = list(filter(lambda x: x % 2 == 0, cleaned_list))

    return cleaned_list, even_numbers

# Example usage
numbers = [3, 6, 8, 7, 5, 9, 2]
cleaned, evens = process_list(numbers)
print("Cleaned List:", cleaned)  # [2, 3, 5, 6, 7, 8, 9]
print("Even Numbers:", evens)    # [2, 6, 8]


Cleaned List: [2, 3, 5, 6, 7, 8, 9]
Even Numbers: [2, 6, 8]


# HAPPY LEARNING