![alt text](<../images/just enough.png>)
# Just Enough Python for AI/Data Science
## Module 3: Numpy- Your First Data Science Power Tool
>This module will ensure you can wrangle numerical data efficiently before tackling larger datasets with pandas. It’s just enough to prep you for serious data crunching.
### Day 8 - Basic Data Math with Numpy
----

##### Overview:

Numpy is one of the most popular libraries in Data Science. If Python is your toolbox, think of Numpy as your Swiss Army Knife—it helps you handle data more efficiently and lays the foundation for working with more complex data tools like Pandas and Scikit-Learn.

Today we will understand:

- Basic mathematical operations on arrays.
- Applying Numpy’s aggregate functions (sum, mean, standard deviation, etc.).
- Useful matrix operations (dot product, transpose, etc.).

#### 1.Mathematical Operations on Numpy Arrays
**Why Not Just Use Python Lists?**
Numpy enables quick element-wise operations, making tasks like adding, subtracting, or multiplying arrays very easy. Let's start with some basics.

**1D Arrays**



In [1]:
import numpy as np


In [2]:

# Create two 1D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise operations
print("Addition:", a + b)  # [1+4, 2+5, 3+6]
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Exponentiation:", a ** 2)  # Square each element


Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Exponentiation: [1 4 9]


**2D Arrays**

In [3]:
# Create two 2D arrays
matrix_1 = np.array([[1, 2], [3, 4]])
matrix_2 = np.array([[5, 6], [7, 8]])

# Element-wise operations
print("Element-wise addition:\n", matrix_1 + matrix_2)
print("Element-wise multiplication:\n", matrix_1 * matrix_2)

# Scalar addition (broadcasting)
print("Matrix + 10:\n", matrix_1 + 10)


Element-wise addition:
 [[ 6  8]
 [10 12]]
Element-wise multiplication:
 [[ 5 12]
 [21 32]]
Matrix + 10:
 [[11 12]
 [13 14]]


#### 2. Aggregate Functions

- Numpy has built-in functions that summarize data, such as finding sums, averages, and extremes. 
- Aggregate functions operate on entire arrays or along specific axes (rows or columns in 2D arrays).

**Basic Aggregates**

In [6]:
array = np.array([1, 4, 5, 3, 6, 5])

print("Sum:", np.sum(array))      # Sum of all elements
print("Mean:", np.mean(array))    # Average
print("Standard Deviation:", np.std(array))  # Spread of the data
print("Minimum:", np.min(array))
print("Maximum:", np.max(array))
print("Product:", np.prod(array))  # Product of all elements


Sum: 24
Mean: 4.0
Standard Deviation: 1.632993161855452
Minimum: 1
Maximum: 6
Product: 1800


**Aggregates on 2D Arrays**
- Use the `axis` parameter to calculate aggregates along rows (`axis=1`) or columns (`axis=0`):

In [7]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])

print("Column sums:", np.sum(matrix, axis=0))  # Sum of each column
print("Row sums:", np.sum(matrix, axis=1))     # Sum of each row
print("Row-wise mean:", np.mean(matrix, axis=1))


Column sums: [5 7 9]
Row sums: [ 6 15]
Row-wise mean: [2. 5.]


#### 3. Matrix Operations in Numpy
**Dot Product**
- The dot product is a fundamental operation in linear algebra (used in machine learning). In Numpy, the `np.dot()` or `@` operator is used to calculate it.

In [8]:
# Dot product of two vectors
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Dot product of vectors:", np.dot(a, b))  # 1*4 + 2*5 + 3*6

# Matrix multiplication
matrix_1 = np.array([[1, 2], [3, 4]])
matrix_2 = np.array([[5, 6], [7, 8]])
print("Matrix multiplication:\n", np.dot(matrix_1, matrix_2))  # OR matrix_1 @ matrix_2



Dot product of vectors: 32
Matrix multiplication:
 [[19 22]
 [43 50]]


##### Matrix Multiplication Explained
![alt text](../images/Matrix-graphic.png)


**Transpose**

Switch rows and columns of a matrix with `.T`:

In [9]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])
print("Original matrix:\n", matrix)
print("Transposed matrix:\n", matrix.T)


Original matrix:
 [[1 2]
 [3 4]
 [5 6]]
Transposed matrix:
 [[1 3 5]
 [2 4 6]]


**Identity Matrices and Inverses**
- Identity Matrix
    - The identity matrix acts as the equivalent of "1" for matrix multiplication.

In [10]:
identity = np.eye(3)  # 3x3 identity matrix
print("Identity Matrix:\n", identity)


Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


- Matrix Inverse
    - The inverse of a matrix is calculated using `np.linalg.inv()`:

In [11]:
matrix = np.array([[1, 2], [3, 4]])
inverse = np.linalg.inv(matrix)
print("Matrix inverse:\n", inverse)

# Verify: Matrix multiplied by its inverse equals the identity matrix
print("Verification (Matrix * Inverse):\n", np.dot(matrix, inverse))


Matrix inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Verification (Matrix * Inverse):
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


----
#### Quick Exercises
1. Perform Aggregate Functions:

    - Create a 3x3 matrix and calculate the sum, mean, and standard deviation of the entire array.
    - Find the minimum for each column and the maximum for each row.
2. Dot Product:

    - Find the dot product of two 1D arrays: [3, 4, 5] and [2, 1, 3].
    - Multiply two 2x2 matrices element-wise and using the dot product.

3. Matrix Manipulation:

    - Create a random 3x3 matrix and compute its transpose and inverse. Verify the inverse by matrix multiplication.


**Please Note:** The solutions to above questions will be present at the end of next session's (Day 9) Notebook.


---- 


### Day 7 Exercise Solution

1. Create the following arrays using Numpy:

    - A 1D array with values from 10 to 50.
    - A 2D array of zeros with shape (4, 3).
    - A random 2x2 matrix.

In [12]:
import numpy as np

# A 1D array with values from 10 to 50
array_1d = np.arange(10, 51)
print("1D array:", array_1d)

# A 2D array of zeros with shape (4, 3)
array_zeros = np.zeros((4, 3))
print("2D array of zeros:\n", array_zeros)

# A random 2x2 matrix
random_matrix = np.random.rand(2, 2)
print("Random 2x2 matrix:\n", random_matrix)


1D array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
2D array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Random 2x2 matrix:
 [[0.33598675 0.11017239]
 [0.42593056 0.28806638]]


2. Perform the following operations:

    - Add 5 to every element of an array.
    - Select all elements greater than 25 in an array.

In [13]:
# Add 5 to every element of an array
array_modified = array_1d + 5
print("Array after adding 5:\n", array_modified)

# Select all elements greater than 25 in an array
greater_than_25 = array_1d[array_1d > 25]
print("Elements greater than 25:\n", greater_than_25)



Array after adding 5:
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
Elements greater than 25:
 [26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50]


3. Reshape a 1D array of size 12 into a 3x4 matrix.

In [14]:
array_reshaped = np.arange(12).reshape(3, 4)
print("Reshaped 3x4 matrix:\n", array_reshaped)


Reshaped 3x4 matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


4. Slice a 2D array to extract:

    - The first row.
    - All rows, but only the second column.

In [15]:
array_2d = np.array([[1, 2, 3], 
                      [4, 5, 6], 
                      [7, 8, 9]])

# Extract the first row
first_row = array_2d[0]
print("First row:", first_row)

# Extract all rows, but only the second column
second_column = array_2d[:, 1]
print("Second column:", second_column)



First row: [1 2 3]
Second column: [2 5 8]


# HAPPY LEARNING