##### Overview:

Pandas is your best friend in Data Science! If Numpy is the Swiss Army Knife for numerical data, Pandas is like a spreadsheet on steroids—it lets you clean, explore, and manipulate massive datasets efficiently while offering way more flexibility than Excel.

Today we will understand:

- What Pandas **DataFrames and Series** are.
- How to load datasets from common file formats (CSV, Excel, etc.).
- Basic exploration and data wrangling tasks using Pandas.
- Accessing and manipulating specific columns and rows.

#### 1. What Is a Pandas DataFrame?
A **DataFrame** is the primary data structure in Pandas, representing tabular data with rows and columns (like an Excel spreadsheet or SQL table). It builds on Numpy arrays but adds labels (row and column names) and features for handling missing/messy data.

**Install Pandas**
Make sure you’ve installed Pandas:


In [1]:
#!pip3 install pandas


Then import it:

In [2]:
import pandas as pd


**Basic Components of a DataFrame**
A DataFrame has:

- **Rows:** Representing individual records/observations, identified by an **index**.
- **Columns**: Representing data fields/attributes, labeled with names (headers).

**Creating a DataFrame**
You can create a DataFrame manually using a Python dictionary:

In [3]:

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["New York", "San Francisco", "Chicago"]
}

df = pd.DataFrame(data)
df



Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35        Chicago

#### 2. Loading Data into a DataFrame
In real-world scenarios, you'll rarely create data manually. Instead, you'll load it from files like **CSV, Excel, or even databases**. 

Let's see how to load a dataset.

**Load a CSV File**
We’ll use a sample dataset—the Titanic dataset, which holds data about Titanic passengers. You can find the dataset online here: https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv.

In [4]:
# Load Titanic dataset
df = pd.read_csv("../data/titanic_dataset.csv")  # Replace with the path to your dataset
df.head()  # First 5 rows


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

Other common Pandas file-loading commands:

- Load **Excel**: pd.read_excel("file.xlsx")
- Load **JSON**: pd.read_json("file.json")
- Load from a **URL**:

In [5]:

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
url_df = pd.read_csv(url)
url_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

#### 3. Basic Exploration of DataFrames

- Once the data is loaded, the first step is to explore and understand its structure.

**Overview of the Dataset**

In [6]:
print(df.info())  # Summary of columns, data types, and missing values


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None


In [7]:
print(df.shape)   # (rows, columns)

(891, 12)


**Preview the Data**

In [8]:
df.head()  # First 5 rows

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [9]:
df.tail()  # Last 3 rows


PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [10]:
df.sample(3)  # Random 3 rows


PassengerId  Survived  Pclass                 Name   Sex   Age  SibSp  \
844          845         0       3  Culumovic, Mr. Jeso  male  17.0      0   
349          350         0       3     Dimic, Mr. Jovan  male  42.0      0   
398          399         0       2     Pain, Dr. Alfred  male  23.0      0   

     Parch  Ticket     Fare Cabin Embarked  
844      0  315090   8.6625   NaN        S  
349      0  315088   8.6625   NaN        S  
398      0  244278  10.5000   NaN        S

**Summary Statistics**
Understand numerical columns at a glance using `.describe().`

In [11]:
df.describe()  # Descriptive stats: mean, min, max, etc.


PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [12]:
df.describe(include='object')  # Descriptive stats for categorical variables

Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [13]:
df.describe(include='all')  # Descriptive stats for all variables

PassengerId    Survived      Pclass                     Name   Sex  \
count    891.000000  891.000000  891.000000                      891   891   
unique          NaN         NaN         NaN                      891     2   
top             NaN         NaN         NaN  Braund, Mr. Owen Harris  male   
freq            NaN         NaN         NaN                        1   577   
mean     446.000000    0.383838    2.308642                      NaN   NaN   
std      257.353842    0.486592    0.836071                      NaN   NaN   
min        1.000000    0.000000    1.000000                      NaN   NaN   
25%      223.500000    0.000000    2.000000                      NaN   NaN   
50%      446.000000    0.000000    3.000000                      NaN   NaN   
75%      668.500000    1.000000    3.000000                      NaN   NaN   
max      891.000000    1.000000    3.000000                      NaN   NaN   

               Age       SibSp       Parch  Ticket        Fare    Cabin  \
count   714.000000  891.000000  891.000000     891  891.000000      204   
unique         NaN         NaN         NaN     681         NaN      147   
top            NaN         NaN         NaN  347082         NaN  B96 B98   
freq           NaN         NaN         NaN       7         NaN        4   
mean     29.699118    0.523008    0.381594     NaN   32.204208      NaN   
std      14.526497    1.102743    0.806057     NaN   49.693429      NaN   
min       0.420000    0.000000    0.000000     NaN    0.000000      NaN   
25%      20.125000    0.000000    0.000000     NaN    7.910400      NaN   
50%      28.000000    0.000000    0.000000     NaN   14.454200      NaN   
75%      38.000000    1.000000    0.000000     NaN   31.000000      NaN   
max      80.000000    8.000000    6.000000     NaN  512.329200      NaN   

       Embarked  
count       889  
unique        3  
top           S  
freq        644  
mean        NaN  
std         NaN  
min         NaN  
25%         NaN  
50%         NaN  
75%         NaN  
max         NaN

**Columns and Index**

In [14]:
# View column names
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [15]:
# Access the index (row labels)
df.index

RangeIndex(start=0, stop=891, step=1)

#### 4. Accessing Columns and Rows
Pandas provides powerful tools to access specific **columns and rows**.

**Accessing Columns**
- DataFrame columns can be accessed like dictionaries:

In [16]:
# Access a single column
df["Age"]  # Access the 'Age' column as a Series


0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [17]:
# Access multiple columns
df[["Name", "Age"]]  # Access 'Name' and 'Age' columns

Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

**Accessing Rows**

- Use `.iloc` (index-based) or `.loc` (label-based):

In [18]:
df.head()  # First 5 rows

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [19]:
# Access rows by position (iloc)
df.iloc[0]     # First row

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [20]:
df.iloc[:3]   # First 3 rows (slice)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [21]:
df.iloc[[0, 2]]  # First and third rows (list of indices)

PassengerId  Survived  Pclass                     Name     Sex   Age  \
0            1         0       3  Braund, Mr. Owen Harris    male  22.0   
2            3         1       3   Heikkinen, Miss. Laina  female  26.0   

   SibSp  Parch            Ticket   Fare Cabin Embarked  
0      1      0         A/5 21171  7.250   NaN        S  
2      0      0  STON/O2. 3101282  7.925   NaN        S

In [22]:
# Access rows by label (loc)
df.loc[0]      # Row with label 0

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [23]:
# Creating a DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35]}

df_1 = pd.DataFrame(data, index=[10, 20, 30])  # Custom row index
df_1.head()  # Display the DataFrame


Name  Age
10    Alice   25
20      Bob   30
30  Charlie   35

In [24]:

print("Using iloc[0]:")
print(df_1.iloc[0])  # Selects the first row based on position


Using iloc[0]:
Name    Alice
Age        25
Name: 10, dtype: object


In [25]:
print("\nUsing loc[0]:")
print(df_1.loc[10])   # ❌ Error! There's no row with index label `0`


Using loc[0]:
Name    Alice
Age        25
Name: 10, dtype: object


**Access Specific Values**

In [26]:
# Value of row 0, column "Age"
df.loc[0, "Age"]


22.0

In [27]:
# Row 2, column 1 using iloc
df.iloc[0, 5]

22.0

#### 5. Subsetting the Data
- Subsetting lets you access data based on specific conditions or rules.

**Filtering Rows Based on Conditions**

In [28]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [29]:
# Filter passengers older than 30
older_than_30 = df[df["Age"] > 30]
older_than_30.head()



PassengerId  Survived  Pclass  \
1             2         1       1   
3             4         1       1   
4             5         0       3   
6             7         0       1   
11           12         1       1   

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                            Allen, Mr. William Henry    male  35.0      0   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   

    Parch    Ticket     Fare Cabin Embarked  
1       0  PC 17599  71.2833   C85        C  
3       0    113803  53.1000  C123        S  
4       0    373450   8.0500   NaN        S  
6       0     17463  51.8625   E46        S  
11      0    113783  26.5500  C103        S

In [30]:
# Filter rows with multiple conditions
rich_male_passengers = df[(df["Sex"] == "male") & (df["Fare"] > 50)]
rich_male_passengers.head()  

PassengerId  Survived  Pclass                            Name   Sex   Age  \
6             7         0       1         McCarthy, Mr. Timothy J  male  54.0   
27           28         0       1  Fortune, Mr. Charles Alexander  male  19.0   
34           35         0       1         Meyer, Mr. Edgar Joseph  male  28.0   
35           36         0       1  Holverson, Mr. Alexander Oskar  male  42.0   
54           55         0       1  Ostby, Mr. Engelhart Cornelius  male  65.0   

    SibSp  Parch    Ticket      Fare        Cabin Embarked  
6       0      0     17463   51.8625          E46        S  
27      3      2     19950  263.0000  C23 C25 C27        S  
34      1      0  PC 17604   82.1708          NaN        C  
35      1      0    113789   52.0000          NaN        S  
54      0      1    113509   61.9792          B30        C

**Select Specific Rows and Columns**

In [31]:
# Select specific rows and columns
subset = df.loc[df["Age"] > 30, ["Name", "Age", "Fare"]]
subset.head()  

Name   Age     Fare
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  71.2833
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  53.1000
4                            Allen, Mr. William Henry  35.0   8.0500
6                             McCarthy, Mr. Timothy J  54.0  51.8625
11                           Bonnell, Miss. Elizabeth  58.0  26.5500

#### 6. Modifying and Adding Data
Once you’ve explored your data, you’ll often want to modify columns or add new ones.

**Adding a New Column**
- You can add new columns using calculations or existing data:

In [32]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [33]:
# Add a new column for 'Age in Months'
df["Age_in_Months"] = df["Age"] * 12
df.head()


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_in_Months  
0      0         A/5 21171   7.2500   NaN        S          264.0  
1      0          PC 17599  71.2833   C85        C          456.0  
2      0  STON/O2. 3101282   7.9250   NaN        S          312.0  
3      0            113803  53.1000  C123        S          420.0  
4      0            373450   8.0500   NaN        S          420.0

**Renaming Columns**
- Use `.rename()` to rename columns.

In [34]:
df = df.rename(columns={"Age": "Passenger_Age"})  # Rename 'Age' column
df.columns


Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Passenger_Age',
       'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked',
       'Age_in_Months'],
      dtype='object')

In [35]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex  Passenger_Age  \
0                            Braund, Mr. Owen Harris    male           22.0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female           38.0   
2                             Heikkinen, Miss. Laina  female           26.0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female           35.0   
4                           Allen, Mr. William Henry    male           35.0   

   SibSp  Parch            Ticket     Fare Cabin Embarked  Age_in_Months  
0      1      0         A/5 21171   7.2500   NaN        S          264.0  
1      1      0          PC 17599  71.2833   C85        C          456.0  
2      0      0  STON/O2. 3101282   7.9250   NaN        S          312.0  
3      1      0            113803  53.1000  C123        S          420.0  
4      0      0            373450   8.0500   NaN        S          420.0

**Modifying Existing Columns**
- You can easily overwrite a column:

In [36]:
df["Fare"] = df["Fare"] * 1.1  # Increase fares by 10%
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex  Passenger_Age  \
0                            Braund, Mr. Owen Harris    male           22.0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female           38.0   
2                             Heikkinen, Miss. Laina  female           26.0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female           35.0   
4                           Allen, Mr. William Henry    male           35.0   

   SibSp  Parch            Ticket      Fare Cabin Embarked  Age_in_Months  
0      1      0         A/5 21171   7.97500   NaN        S          264.0  
1      1      0          PC 17599  78.41163   C85        C          456.0  
2      0      0  STON/O2. 3101282   8.71750   NaN        S          312.0  
3      1      0            113803  58.41000  C123        S          420.0  
4      0      0            373450   8.85500   NaN        S          420.0

#### 7. Exporting DataFrames
- After transforming or cleaning your data, export it for further use:

In [37]:
# Save to CSV
df.to_csv("../artifacts/titanic_cleaned.csv", index=False)

# # Save to Excel
# df.to_excel("titanic_cleaned.xlsx", index=False)

# # Save to JSON
# df.to_json("titanic_cleaned.json")



----
#### Quick Exercises
1. Download the Titanic dataset.
2. Load the dataset into a Pandas DataFrame.
3. Answer the following:
    - What are the column names?
    - How many rows and columns are there?
    - What are the data types of the columns?
4. Perform these operations:
    - Access the first 5 rows of the dataset.
    - Select and print the "Name" and "Age" columns.
    - Filter and print passengers above the age of 40.
5. (Bonus) Add a new column called Family Size that’s the sum of SibSp and Parch (siblings/spouse + parents/children).

**Please Note:** The solutions to above questions will be present at the end of next session's (Day 10: Pandas - Cleaning Data) Notebook.


---- 


### Day 8 Exercise Solution

1. Perform Aggregate Functions:

    - Create a 3x3 matrix and calculate the sum, mean, and standard deviation of the entire array.
    - Find the minimum for each column and the maximum for each row.

In [38]:
import numpy as np

# Creating a 3x3 matrix with random integers between 1 and 10
matrix_3x3 = np.random.randint(1, 10, (3, 3))

print("3x3 Matrix:")
print(matrix_3x3)

3x3 Matrix:
[[4 5 4]
 [7 4 1]
 [6 5 9]]


In [39]:
sum_matrix = np.sum(matrix_3x3)  # Sum of all elements
print("Sum of all elements:", sum_matrix)



Sum of all elements: 45


In [40]:
mean_matrix = np.mean(matrix_3x3)  # Mean of all elements
print("Mean of all elements:", mean_matrix)

Mean of all elements: 5.0


In [41]:
std_matrix = np.std(matrix_3x3)  # Standard deviation
print("Standard deviation of all elements:", std_matrix)

Standard deviation of all elements: 2.1081851067789197


In [42]:
min_per_column = np.min(matrix_3x3, axis=0)  # Minimum for each column
print("Minimum per column:", min_per_column)


Minimum per column: [4 4 1]


In [43]:
max_per_row = np.max(matrix_3x3, axis=1)  # Maximum for each row
print("Maximum per row:", max_per_row)

Maximum per row: [5 7 9]


2. Dot Product:

    - Find the dot product of two 1D arrays: [3, 4, 5] and [2, 1, 3].
    - Multiply two 2x2 matrices element-wise and using the dot product.

In [44]:
array_1 = np.array([3, 4, 5])
array_2 = np.array([2, 1, 3])
dot_product_1d = np.dot(array_1, array_2)  # Dot product of two 1D arrays
print("Dot product of 1D arrays:", dot_product_1d)



Dot product of 1D arrays: 25


In [45]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
elementwise_product = matrix_a * matrix_b  # Element-wise multiplication
dot_product_2d = np.dot(matrix_a, matrix_b)  # Dot product of two matrices
print("Element-wise product of matrices:\n", elementwise_product)
print("Dot product of matrices:\n", dot_product_2d)

Element-wise product of matrices:
 [[ 5 12]
 [21 32]]
Dot product of matrices:
 [[19 22]
 [43 50]]


3. Matrix Manipulation:

    - Create a random 3x3 matrix and compute its transpose and inverse. Verify the inverse by matrix multiplication

In [46]:
random_matrix = np.random.rand(3, 3)  # Creating a random 3x3 matrix
print("Random 3x3 matrix:\n", random_matrix)



Random 3x3 matrix:
 [[0.58059501 0.05382555 0.84494081]
 [0.01602872 0.54214209 0.44404662]
 [0.37460189 0.37233272 0.25590189]]


In [47]:
transpose_matrix = np.transpose(random_matrix)  # Computing the transpose
print("Transpose of the matrix:\n", transpose_matrix)




Transpose of the matrix:
 [[0.58059501 0.01602872 0.37460189]
 [0.05382555 0.54214209 0.37233272]
 [0.84494081 0.44404662 0.25590189]]


In [48]:
inverse_matrix = np.linalg.inv(random_matrix)  # Computing the inverse
print("Inverse of the matrix:\n", inverse_matrix)

Inverse of the matrix:
 [[ 0.15351057 -1.73622099  2.50586545]
 [-0.93636692  0.96927698  1.40979985]
 [ 1.13768087  1.13128561 -1.81169639]]


In [49]:
# Verify inverse using matrix multiplication
identity_matrix = np.dot(random_matrix, inverse_matrix)
print("Product of matrix and its inverse (should be identity):\n", identity_matrix)


Product of matrix and its inverse (should be identity):
 [[ 1.00000000e+00  1.11022302e-16  2.22044605e-16]
 [ 1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.11022302e-16  1.00000000e+00]]


# HAPPY LEARNING